name: rmapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

  # Local storage
  shared_preferences: ^2.5.3

  # Sensors / Location (ของเดิมคุณ)
  location: ^8.0.1
  sensors_plus: ^7.0.0
  device_calendar: ^4.3.3
  fl_chart: ^1.1.1
  geolocator: ^14.0.2

  # สำหรับเปิดลิงก์/ไฟล์ และสร้างไฟล์ .ics
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  open_filex: ^4.7.0

  # สำหรับ “เขียนลงปฏิทินเครื่อง”
  
  timezone: ^0.9.4

  # (ตัวนี้ไม่จำเป็นแล้ว ถ้าไม่ได้ใช้ flow add_2_calendar สามารถลบได้)
  add_2_calendar: ^3.0.1

# ใช้เรียก model มาใช้งาน
  tflite_flutter: ^0.11.0
  #tflite_flutter_plus: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/lstm_activity_model_float32.tflite
