// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH4jIwfohhR0A8DRfVYVIuh55HsQVQEtk',
    appId: '1:45382752673:web:b8daf9e53d1cabde1553e0',
    messagingSenderId: '45382752673',
    projectId: 'rmapp-66582',
    authDomain: 'rmapp-66582.firebaseapp.com',
    storageBucket: 'rmapp-66582.firebasestorage.app',
    measurementId: 'G-K6XH7MFS6G',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS1tAjZa9BAImxO5e_F9oymx9bV8qjpN4',
    appId: '1:45382752673:ios:5b364b2c519ac01a1553e0',
    messagingSenderId: '45382752673',
    projectId: 'rmapp-66582',
    storageBucket: 'rmapp-66582.firebasestorage.app',
    iosBundleId: 'com.example.rmapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS1tAjZa9BAImxO5e_F9oymx9bV8qjpN4',
    appId: '1:45382752673:ios:5b364b2c519ac01a1553e0',
    messagingSenderId: '45382752673',
    projectId: 'rmapp-66582',
    storageBucket: 'rmapp-66582.firebasestorage.app',
    iosBundleId: 'com.example.rmapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgQ_vCohIhs5y7V1862xr16XuDUdYnxKU',
    appId: '1:45382752673:android:2c39097ff59f01951553e0',
    messagingSenderId: '45382752673',
    projectId: 'rmapp-66582',
    storageBucket: 'rmapp-66582.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH4jIwfohhR0A8DRfVYVIuh55HsQVQEtk',
    appId: '1:45382752673:web:92763bc4ae52e0b31553e0',
    messagingSenderId: '45382752673',
    projectId: 'rmapp-66582',
    authDomain: 'rmapp-66582.firebaseapp.com',
    storageBucket: 'rmapp-66582.firebasestorage.app',
    measurementId: 'G-LLG4GPK79L',
  );

}